name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: read-all

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - id: tag
        run: echo "SHORTREF=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: google-github-actions/auth@v3
        with:
          project_id: getpipe-sh
          workload_identity_provider: projects/1059511554636/locations/global/workloadIdentityPools/github/providers/getpipe-sh
          service_account: github-actions@getpipe-sh.iam.gserviceaccount.com
          export_environment_variables: true
      - run: gcloud auth configure-docker gcr.io
      - uses: google-github-actions/setup-gcloud@v3
      - uses: docker/setup-buildx-action@v4
      - name: build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
          push: true
          tags: gcr.io/getpipe-sh/server:${{steps.tag.outputs.SHORTREF}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: server
          image: gcr.io/getpipe-sh/server:${{steps.tag.outputs.SHORTREF}}
